### ISSUE TITLE
Saving issue

### ISSUE THREAD

**Issue by steveg8879** [mattiasghodsian/wooCMFS#1]
Hello,

First let me say thanks for writing a simple, yet effective plugin.  I'm on a new project for a side gig I have and this is exactly what I need.  I did notice there was issues with saving the product once the meta fields are entered.  I fixed the issue and will be submitting a PR.

**Comment by mattiasghodsian** [comment]
> Hello,
> 
> First let me say thanks for writing a simple, yet effective plugin. I'm on a new project for a side gig I have and this is exactly what I need. I did notice there was issues with saving the product once the meta fields are entered. I fixed the issue and will be submitting a PR.

Thank you @steveg8879, Sorry for the late reply. I'll check when you submit
